govuk-one-login/authentication-acceptance-tests

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/accountmanagement/AccountManagementStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/accountmanagement/account_management.feature, run-acceptance-tests.sh
Basic acceptance test for account management launch.
Make sure deployments don't break account management.
https://github.com/alphagov/di-infrastructure/pull/38
=> BAU: basic acceptance test for account management launch

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/legal_and_policy_pages.feature
- Comment out Accessibility statement tests
- It now opens a new tab but as this is blocking lets comment it out for now and come back to this.
=> BAU - Comment out Accessibility statement tests

.env.sample, .gitignore, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/registration_journey.feature, docker-compose.yml, run-acceptance-tests.sh
Cucumber test changes to support sign-up using a test client
Expand acceptance test coverage. 
A pipeline change is required before merge.
=> GOVSI-619: cucumber test changes to support sign-up using a test client

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature
Add delete account scenario
Increase coverage.
https://github.com/alphagov/di-infrastructure/pull/121
=> GOVSI-1060: add delete account scenario

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
Update tests to support new sign in page.
=> Update AC with sign in and create page changes

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature
- Add page load and implicit wait timeouts and set to 30 seconds
- Correct indentation of feature files
Test are randomly failing in pipeline, increasing the timeout seems to help.
=> Bau add timeouts

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
Update tests to support new state machine
Support small changes required to implement the state machine.
=> AUTH-1063: Update tests to support new state machine

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
Update tests for account created changes
=> Update tests for account created changes

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature
Submit button fix
So the AC tests can run with the change.
=> submit button fix

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java
Update constructor calls for WebDriverWait.
Fixes build broken by #71 (a Selenium update).
#71
=> BAU: fix broken build

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java, acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature
Acceptance test for scenario where a user attempts to change their phone number with the phone number they have already registered their account against.
Following the fix that as implemented, this scenario is identified as valuable in AC tests coverage.
=> Aut 477 ac tests user attempting to use current phone number as new phone number

acceptance-tests/build.gradle
Reverts alphagov/di-authentication-acceptance-tests#120
=> Revert "Bump dependencyVersions.cucumber_version from 7.4.1 to 7.6.0"

docker-compose.yml, nginx/manifest.yml
Upgrade to latest selenium-firefox image.
Current image is outdated.
=> BAU: Upgrade to latest selenium-firefox image

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature
Add debug for setup-authenticator-app
Seeing intermittent issues when entering a code
=> BAU: Add debug for setup-authenticator-app

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java, acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature
Changes required on the back of changes in AUT-731
So the AC tests reflect the changes.
=> Edited auth app feature file and registration step definition

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/020_locked_accounts.feature
Reverts alphagov/di-authentication-acceptance-tests#147
=> Revert "ACI-7: Do not block email when validation code entered incorrectly max times for new account"

acceptance-tests/build.gradle, build.gradle
Upgrading our packages in build.gradle.
To get improvements of new versions.
=> Package upgrades in build.gradle

README.md, acceptance-tests/build.gradle, acceptance-tests/src/test/resources/allure.properties
Integration of the Acceptance tests with Allure reporting.
To meet the request for it.
=> Aut 820 integrate tests with allure report

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/003_legal_and_policy_pages.feature
Temporarily disabling this scenario as user keeps getting deleted.
To unblock the pipeline.
=> Commenting out T&C scenario until user is sorted.

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Axe.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
What?
Refactoring our feature file for auth app and it corresponding steps in step definitions
Why?
To reduce the line of code and make the file more readable
Related PRs
=> Featurefilerefactor 2faauth

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Axe.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
Reverts alphagov/di-authentication-acceptance-tests#171
=> Revert "Featurefilerefactor 2faauth"

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Axe.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
Reverts alphagov/di-authentication-acceptance-tests#172
=> Revert "Revert "Featurefilerefactor 2faauth""

acceptance-tests/src/test/java/uk/gov/di/test/pages/RegistrationPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/015_incomplete_registration.feature
Refactoring of Registration Feature file
To make the feature file more readable and reducing the line of code
=> Registration

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/020_locked_accounts.feature
Refactoring of remaining feature files
To make it more readable
=> Refactoring feature files for extsing users

acceptance-tests/src/test/java/uk/gov/di/test/pages/AccountManagementPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/SupportPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Support.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/025_doc_app_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature, reset-test-data.sh
Add acceptance tests for international phone numbers.
To test functional changes implemented for IPN.
=> AUT-1056: Add acceptance tests for international phone numbers

acceptance-tests/src/test/java/uk/gov/di/test/pages/SupportPage.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
Tests updated to reflect radio button text change to '...another country', instead of '...a different country'
Confirmed by Kim that this is what is required.
=> updated radio button text

reset-test-data.sh
Reset passwords for reset password test users.
Test scenarios for reset password and require password reset are based on changing the passwords of existing seeded test users.  Need to reset these passwords after the scenarios have run.
https://github.com/alphagov/di-infrastructure/pull/474
=> AUT-1068: Reset passwords for reset password test users

acceptance-tests/src/test/java/uk/gov/di/test/pages/CheckYourEmailPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/ResetYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature, reset-test-data.sh
Added new acceptance test for password reset
Password reset functionality not currently covered. This is a longstanding ticket that required some updates to stub, which have now been done, therefore unblocking this ticket.
=> AUT-915 - added pw reset test

.gitignore, acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java
Updated references to sign-in to bring in line with changes in AUT-1116
Sign-in link has been changed to a button.
=> AUT-1140 update sign in button refs

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature
Added new acc test for when existing user has a current password that is on the top 100k password list and is forced to change it.
To fill a gap in test coverage.
=> AUT-1068 enforce 100k password check

acceptance-tests/src/test/java/uk/gov/di/test/pages/NoGovUkOneLoginFoundPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/RegistrationPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
Replaced existing test with a different variation following rp s2 config changes. Previous test commented out with a view to re-instating in future following rp stub strategy review.
To accomodate rp s2 config changes.
=> AUT-1198 - updated tests following rp s2 config change

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature
Revert page title changes.
Content changes are being reverted pending review.
#224 
#223
=> AUT-955: Revert page title changes

reset-test-data.sh
Refactor reset-test-data script into functions.
Reduces repetition and makes the functions reusable.
=> BAU: Refactor reset-test-data script into functions

reset-test-data.sh
- Reset state of account recovery test users.
- Allow environment variable override in the .env file for the environment name so that the script can be used against both the dev and build environments.
```
TEST_USER_ACCOUNT_RECOVERY_EMAIL_1=di-authentication-tech+account-recovery1@digital.cabinet-office.gov.uk <--- sms user. At end of test run this user will need to be set back to sms user and pw reset to TEST_USER_PASSWORD
TEST_USER_ACCOUNT_RECOVERY_EMAIL_2=di-authentication-tech+account-recovery2@digital.cabinet-office.gov.uk <--- auth app user. At end of test run this user will need to be set back to auth app user and pw reset
TEST_USER_ACCOUNT_RECOVERY_EMAIL_3=di-authentication-tech+account-recovery3@digital.cabinet-office.gov.uk <--- sms user. At end of run user account to be reset …
```
=> AUT-1320: Reset state of account recovery test users

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocApp.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java
Created a new Hooks.java file to hold all hooks
Hooks were duplicated across all step def files. Now held in one central location.
=> AUT-1336 remove hook duplication

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
Moved code from 'User clears cookies' Cucumber step to Before hook.
A small contribution towards reducing Cucumber step count.
=> AUT-1342 moved clear cookies from cucumber step to Before hook

acceptance-tests/src/test/java/uk/gov/di/test/pages/TermsAndConditionsPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature
Re-instated the terms and conditions test, and modified a little to get it working again.
This test has been commented out since before my time, but is required.
=> AUT-1350 reinstated terms and conditions test and got it working again

acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java
Created a 'Enter your password' page object to separate out components from the currently generic LoginPage page object.
Also got rid of quite a few unused steps.
The first of several new page objects with the objective of making the tests more easily readable/manageable.
=> AUT-1345 enter your password page object

acceptance-tests/src/test/java/uk/gov/di/test/pages/CreateOrSignInPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourEmailAddressPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourEmailAddressToSignInPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/RegistrationPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/ResetYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
Splitting out more of LoginPage page object to separate page objects.
Also, discovered and got rid of more redundant steps/code.
To make tests more easily readable and maintainable.
=> AUT-1355 split out more of loginpage to separate page objects

acceptance-tests/src/test/java/uk/gov/di/test/pages/CheckYourEmailPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/CheckYourPhonePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/ChooseHowToGetSecurityCodesPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/CreateOrSignInPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/CreateYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterThe6DigitSecurityCodeShownInYourAuthenticatorAppPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourEmailAddressPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourMobilePhoneNumberPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/GetSecurityCodePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/ResetYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/RpStubPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/SetUpAnAuthenticatorAppPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/YouAskedToResendTheSecurityCodeTooManyTimesPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthAppStub.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
AUT-1361 - created more page objects and updated accordingly. cleared out more redundancy and duplication
Created more page objects to move towards phasing out the existing Login and Registration ones that held everything.
Updated the old references to point to the new page objects.
Removed redundant code.
Removed/consolidated duplicated steps/code.
To get rid of the existing Login and Registration page objects (still a little more to do for Login). Make the whole framework more readable/maintainable.
=> AUT-1361 - created more page objects and updated accordingly. cleared out more redundancy and duplication

acceptance-tests/src/test/java/uk/gov/di/test/pages/ChooseHowToGetSecurityCodesPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Page_state_preservation.feature, ci/tasks/reset-test-data.yml, scripts/reset-test-users.sh
Added acceptance tests for page state preservation after using Back link.
To go with the dev changes just made to the front end for page state preservation.
=> AUT-1300 - added acceptance tests for page state preservation

acceptance-tests/src/test/java/uk/gov/di/test/pages/CheckYourEmailPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/YouveChangedHowYouGetSecurityCodesPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocApp.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Added tests for Account Recovery.
Account Recovery dev pretty much complete.
=> AUT-1092 - added account recovery tests

.github/workflows/pre-merge-checks.yml, .github/workflows/sonar-analysis-on-merge.yml, build.gradle
- Add Sonar scan on PR and post-merge
- Add Spotless checks on PR
- To improve code quality and security
=> AUT-1612: Add Sonar and Spotless scan

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java
A couple of tweaks to enable the tests to run successfully in Firefox.
2 or 3 tests had started failing in the pipeline (firefox).
=> fixed things that were an issue in firefox

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/TermsAndConditionsPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicyStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java
Stripped out unused code.
To reduce code
=> AUT-1828 - stripped out unused code

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/FooterPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/SupportPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/SupportStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Welsh_support_pages.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Added tests for Welsh support pages.
Because there weren't any.
=> AUT-1833 added tests for welsh support pages

.github/CODEOWNERS, .github/workflows/build-and-push-tests-manual.yaml
Adding manual trigger workflow to build and push chrome testing image 
To run  the Acceptance testing on chrome
=> Adding Manual workflow To build image using github action

.github/workflows/build-and-push-tests-manual.yaml, .github/workflows/build-and-push-tests.yaml
BAU Change to move AWS Credentials to Git Hub Secret
=> Masking AWS secret in Git Hub Action role

scripts/database.sh
Adds functionality (currently unused) to add account interventions state for:
* A blocked user
* A suspended user
* A user who has been mandated to reset their password
So that we can test out the new account interventions flow
=> AUT-1866: add functions to add interventions users

scripts/database.sh
Include sector in internal common subject id calculation for account interventions stub data
Sector was missing so the ics was incorrect.
#304
=> AUT-2132: Include sector in internal common subject id calculation for account interventions stub data

acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Please include a summary of the change.
Please include reason for the change and any other relevant context.
=> Update test for AUT-1553 test for 15 mins time out log back in

acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Please include a summary of the change.
Please include reason for the change and any other relevant context.
=> Update error message

scripts/database.sh
Fix broken query in createOrUpdateInterventionsUser
Missing quotes around email.
#311
=> AUT-2132: Fix broken query in createOrUpdateInterventionsUser

.env.sample, acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocAppStepDef.java
Update references to RP stub
Stub is being migrated off paas and has a new url
=> ATO-383: Update references to new stub

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocAppStepDef.java
Please include a summary of the change.
Please include reason for the change and any other relevant context.
=> BAU: correct default docapp URL

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/CreateOrSignInPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/NoGovUkOneLoginFoundPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
Added some ExpectedCondition waits.
An attempt to reduce test flakiness.
=> Added in some explicit waits

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java
Added some more explicit waits.
Another attempt to resolve flakiness when run in the pipeline.
=> added more explicit waits to try to resolve pipeline flakiness

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/CreateOrSignInPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/NoGovUkOneLoginFoundPage.java
Replaced waitForClickable with a wait for page readyState = complete 
Another attempt to reduce flakiness
=> added a wait for page readyState to try and reduce flakiness

scripts/database.sh
Reverts govuk-one-login/authentication-acceptance-tests#339
=> Revert "BAU: Additional logging for internal common subject id creation"

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java
Added some hardcoded waits
To see if it helps to improve flakiness
=> Next attempt at addressing flakiness

scripts/database.sh
Add additional logging for test data setup in the pipeline.
There are errors happening when creating users for account interventions.
=> BAU: Add additional logging for test data setup in the pipeline

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/SupportStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Update title for sign in or create screen.
Title text has been updated for the page in both en and cy
#1542
=> BAU: Update title for sign in or create screen

.github/workflows/build-and-push-tests-dev.yaml, scripts/trigger-gha-current-branch.sh
Adding Dev workflow for DEV acceptance image
Building Dev environment
Run ./scripts/trigger-gha-current-branch.sh , this should trigger the Workflow in git Action
=> Adding Dev workflow for DEV acceptance image

acceptance-tests/src/test/java/uk/gov/di/test/pages/CheckYourPhonePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourMobilePhoneNumberPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/EnterYourPasswordPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LockoutPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/YouHaveAGOVUKOneLoginPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LockoutsStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java
Refactored some of the steps for 2hr lockout tests
For better readability and tidiness
=> Refactored lockout tests

reset-test-data.sh, run-acceptance-tests-against-dev-env.sh
Add the dev to the list of environments agains which you can run acceptance tests
=> BAU: add dev to environment list

.github/workflows/build-and-push-tests-SP.yaml, .github/workflows/build-and-push-tests-dev.yaml
AUT-3504 build and push acceptance test image on new Build account ECR repo 
We need to run acceptance test  on new Build Frontend using secure pipeline
=> AUT-3504 build and push acceptance test image new ecr

.github/workflows/build-and-push-tests-SP.yaml
BAU moving env variable To github secrets
=> BAU moving env variable To github secrets

acceptance-tests/src/test/java/uk/gov/di/test/pages/RpStubPage.java
=> BAU: Log out the value of the One Login session ID before starting journey

acceptance-tests/build.gradle
Uplift to latest selenium version 4.24.0
In case this resolves intermittent test failures.
=> BAU: Uplift to latest selenium version 4.24.0

acceptance-tests/build.gradle, acceptance-tests/src/test/java/uk/gov/di/test/utils/Driver.java
We are trying to isolate a source of flakiness
=> BAU: Revert selenium version from 4.23 to 4.5

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RpStubStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature
Sometimes we start the journey on a different page, allow for this.
=> BAU: Don't always assume the post-rp-stub page

.github/workflows/pre-commit.yml
=> BAU: exclude dependabot PRs from pre-commit checks.

run-acceptance-tests.sh
Managed to swallow the failure exit code. Fixed that now.
=> BAU: Exit correctly on test failure

.run/Template Cucumber Java.run.xml
This allows other people to quickly use the working
run template from the repo, rather than sharing individual settings
which is confusing
code review / 'trust me bro'
=> BAU: store run config template in VCS

acceptance-tests/build.gradle
Reverts govuk-one-login/authentication-acceptance-tests#481
=> Revert "BAU: Revert Selenium to 4.11.0"

acceptance-tests/build.gradle, acceptance-tests/src/test/java/uk/gov/di/test/services/DynamoDbService.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_account_recovery.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_create_account.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_sign_in.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Page_state_preservation.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature, run-acceptance-tests.sh, run-tests.sh
Get Tom's acceptance tests working on the secure pipeline
Tested by running the test image in build and staging environments. 
Test report links: 
- build: [here](https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/058264536367/testReports/reports/Test-frontend-pipeline-TestReports/Test-frontend-pipeline-TestReports%3A1b3f4d94-e540-4ba3-97ab-683c56531c9b?region=eu-west-2&test-reports-meta=eyJmIjp7InRleHQiOiIifSwicyI6eyJkaXJlY3Rpb24iOjEsInByb3BlcnR5Ijoic3RhdHVzIn0sIm4iOjIwLCJpIjowfQ)
- staging: [here](https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/851725205974/testReports/reports/Test-frontend-pipeline-TestReports/Test-frontend-pipeline-TestReports%3A2f6d34e1-22b8-4042-bd14-4f76cde343b7?region=eu-west-2&test-reports-meta=eyJmIjp7InRleHQiOiIifSwicyI6eyJkaXJlY3Rpb24iOjE …
=> AUT-3870: tag tests for the sp pipeline

acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_create_account.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_sign_in.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Page_state_preservation.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature
Currently there is an issue with with the new orchestration stub that prevents some of the journey's completing successfully.  While a fix is worked on we will tag those tests that run successfully in dev.
1. Code Review
2. Run from local against one of the dev accounts with the cucumber tag of @build.
=> BAU: Add new tag `dev` to the tests that run successfully in dev.

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/UserLifecycleStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
=> Add tests for mfa reset happy and negative tests

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/LockoutPage.java, acceptance-tests/src/test/java/uk/gov/di/test/pages/OrchestrationStubStartPage.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LockoutsStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Strategic_App.feature
=> AUT-3857-Strategic-App-&-MFA-Reset-Content-Change

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
=> AUT-3931 Changes for MFA Error Help Screen

acceptance-tests/build.gradle, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
=> New PR to implement under-development tag for dev tests

acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_account_recovery.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Reauthentication.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
=> Update Tags for excluding old MFA Test in dev pipeline

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
The MFA reset test scenario that navigates to the contact page owned by Home fails when it is run in the pipeline.  It passes when run locally so is likely an access privs issue. Excluding from dev until this is resolved.
1. Code Review
=> BAU: Exclude test from that dev.

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
This is for additional test for AUT - 3931 and addressing Tagging issue
=> AUT-3931 and Tagging

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
Two new test scenarios have been added to test reset MFA without IPV.  They have been written to work with the new stub and so are failing in build.  Tagging them as @under-development to unblock the pipeline.
1. Code Review
=> BAU: Exclude failing tests from build.

acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature
Reverts govuk-one-login/authentication-acceptance-tests#589
=> Revert "@underdevelopment tag has been removed"

acceptance-tests/build.gradle, build.gradle
Reverts govuk-one-login/authentication-acceptance-tests#602
=> Revert "BAU: Bump the gradle-all-dependencies group across 1 directory with 6 updates"

.github/workflows/build-and-push-tests-SP.yaml, .github/workflows/build-and-push-tests.yaml
Having issues with acceptance tests runs and trying a no cache build first
1. Code Review
=> BAU: Temporarly enable --no-cache when building image

.github/workflows/build-and-push-tests.yaml
Going to try this later, as tag doesn't exist atm
1. Code Review
=> BAU: Remove tag for commit sha

sp.Dockerfile
The script should be in the root, not in `/scripts`.
Code Review
=> BAU: fix script path in Dockerfile

docker/run-tests-sp.sh
Force SP tests to not use SSM.
As we no longer use the original 'run-acceptance-tests.sh' script, it doesn't disable SSM as it used to.
Now, we don't bother shelling out at all, and bring the logic into this script
Code review
=> BAU: Force SP tests to not use SSM

docker/run-tests-sp.sh
=> BAU: actually, do use SSM, just also export envars

docker/run-acceptance-tests.sh, docker/run-tests-sp.sh
All the iteration since cc3f929acfcf6c3809651364aad3995edfc279db
has been unnecessary, except for sourcing `/test/.env`.
This is actually all that's needed.
=> BAU: Actually fix the problem (envars)

.github/workflows/build-and-push-tests-SP.yaml, .github/workflows/build-and-push-tests-dev.yaml, .github/workflows/build-and-push-tests.yaml, .github/workflows/pre-commit.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/require-pinned-github-actions.yml, .github/workflows/sonar-analysis-on-merge.yml
=> BAU: require pinned actions

acceptance-tests/src/test/java/uk/gov/di/test/entity/MFAMethod.java
This is actually a string, not int.
1. Code Review
=> AUT-1416: Correct `MFAMethod.mfaIdentifier` type

acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-auth-app-user.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature
Minor changes to align the scenario steps with the StedDefs implementation 
1. Code Review
=> AUT-4309: Correct terminology for MFA tests

acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature
AUT-1416- To validate sms back login
<!-- Links to PRs in other repositories that are relevant to this PR.
=> AUT-1416- To validate sms back up login

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature
This is an acceptance test to cover the AUT-4008 we missed. 
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -a`
1. Ensure that resources `x`, `y` and `z` were not changed
1. Visit [some url](https://some.sandpit.url/to/visit)
1. Log in
1. Ensure `x` message appears in a modal
-->
=> AUT-4008- To validate sms backup with Auth App

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/utils/Constants.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/account_management.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-auth-app-user.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature
Method Management API tests exqapnded for adding international phone number as backup MFA
=> AUT-4309 Addded International Phone Number in MM API Tests

acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature
=> AUT-4256 Password reset with back-up method added

.gitignore, Dockerfile, README.md, docker/run-api-tests.sh, docker/run-tests.sh, docker/run-ui-tests.sh, run-acceptance-tests.sh, rundocker.sh
The env vars are created from parameter store in the same way for both UI and API tests.
Renamed files to better reflect the two account approach - UI and API.
More updates to the README
1. Code review
2. Run the API and UI tests against the dev end and the build env.
3. Create override files for both the UI and API tests, confirm they are applied.
4. Check the output from the tests is correct, i.e. correct list env vars created, correct overrides applied.
5. Check the cucumber test reports are created in the tmp folder.
6. Check README still accurately describes the repo and how to use it.
=> BAU: QoL improvements env vars, script names, etc.

acceptance-tests/src/test/java/uk/gov/di/test/services/ApiInteractionsService.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/MFAMethodsAPIStepdefs.java
Fix for sending otp and checking results.
Reworked stepdefs as what the methods were actually doing wasn't reflected in the step description.
1. Code Review
2. Run tests and check logs to confirm correct.
=> AUT-4384: WIP fixing send otp

acceptance-tests/src/test/java/uk/gov/di/test/services/ApiInteractionsService.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/MFAMethodsAPIStepdefs.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-auth-app-user.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature
Update the API tests for method management to vaidate the update of backup phone number with county code. Update meethod to check if the backup phonne nuber is updated with correct assertions.
=> Refactor Method Management API tests to validate the update of backup phone number against normalized phone number starting with country code

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java
Whilst updating the scenarios on the previous commit we missed updating this StepDef to use the new text.
1. Code Review
=> AUT-4384: Update stepdef to reflect scenario

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java, acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java, acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature
Validate Different scenario's. to test Reauthenctication journey using backup MFA's
=> AUT-4198 - Test Reauth using Backup MFA

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature, acceptance-tests/src/test/resources/uk/gov/di/test/features/mfa-reset/migrated-users/mfa-reset-migrated.feature
Re-enable MFA reset tests
1. Code Review
2. Run both UI and API test suites from local against the build environment.
=> BAU: Re-enable MFA reset tests

acceptance-tests/build.gradle, gradle/libs.versions.toml
BAU: fix critical Vulnerable dependency
1. https://github.com/govuk-one-login/authentication-acceptance-tests/security/dependabot/3
2. https://github.com/govuk-one-login/authentication-acceptance-tests/security/dependabot/2
1. Code Review
1. Deploy to Dev and check if acceptance test are working
=> BAU: fix critical Vulnerable dependency
