govuk-one-login/authentication-acceptance-tests

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/StepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/registration_journey.feature
nginx/manifest.yml
nginx/nginx.conf

Add nginx for Selenium in the pipeline.
Limit test scenarios to those currently implemented.
An nginx route service is needed to run Selenium in a pipeline.
Only a small part of the scenarios are currently available to test.

BAU: add nginx for Selenium in the pipeline, restrict scenarios

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RunCucumberTest.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/legal_and_policy_pages.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/login_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/registration_journey.feature
build.gradle
gradle.properties
run-acceptance-tests.sh

Refactor cucumber step definitions to support additional scenarios.
Reword steps for new and existing user scenarios.
Add scenarios to check accessibility and cookies pages links.
Add spotless + reformat.
All the step definitions were in one file which is not scalable.

BAU: refactor cucumber step definitions to support additional scenarios

---

nginx/manifest.yml

- Add Docker Hub username to manifest
- Password is provided via `CF_DOCKER_PASSWORD` environment inject in pipeline.
Required to avoid Docker Hub rate limiting. Previous PR was raised to provide username on command in pipeline, but that doesn't work when using a manifest.
https://github.com/alphagov/di-infrastructure/pull/26
https://github.com/alphagov/di-infrastructure/pull/24

BAU: Add Docker Hub username to manifest

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/accountmanagement/AccountManagementStepDefinitions.java

- Change expected page title to "Create a GOV.UK account or sign in - GOV.UK account"
The content has changed and the page titles have changed.

BAU: Fix expected page titles in acceptance tests

---

nginx/manifest.yml

- Currently seeing the following error `writing blob to tempfile: uncompressed layer size exceeds quota` when trying to deploy. I believe this is caused because the docker image is larger than the disk size. Increase the disk size so it can handle the docker image
- So selenium can deploy without error

BAU - Increase disk quota

---

nginx/manifest.yml

Pin selenium docker image.
Image tag was set to 'latest' and the latest version is failing.
Set back to previous.

BAU: pin selenium docker image

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java

Fix update password by maintaining the session between scenarios ( closeWebdriver() call )
Some additional spotless formatting.
Update password test failing as the session is cleared before the test starts.
#31

BAU: fix update password by maintaining the session between scenarios

---

.env.sample
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
docker-compose.yml
run-acceptance-tests.sh

Add registration validation scenarios.
- Test invalid data for email address, six digit code and password in the signup journey.
- Add local support for testing in Chrome.
Increase test and browser coverage.

BAU: add registration validation scenarios

---

.env.sample
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java

Add debug mode
- Let tester interact with a local browser when running the tests.
- Pauses to let tester enter OTP codes.
Separate flag for headless mode.
Provide a configurable way to build and test scenarios in a local browser.

BAU: add debug mode

---

README.md

Add a readme for the acceptance tests.
So people know how to run and change the tests.

AUTH-1138: add a readme for the acceptance tests

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java

Use String for uri rather than Java URI to support local Windows execution.
Tested on a local Windows box.
Seeing errors when trying to parse strings to URI on Windows.  Given that the URI are consumed as String by Selenium anyway we can just remove the conversion.  There's some loss in not being able to retrieve component parts of the URI for testing, but this lets us move forward with running on Windows.

AUTH-1405: use String for uri rather than Java URI to support local Windows execution

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

Acceptance tests for scenario #7 on the spreadsheet. Where an existing user tries to create an account even though they already have an account.
Need to increase coverage of automation and this scenario is required.

AUTH-1414: acceptance tests with existing email

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java

Update account created page title in test.
Account created page title was changed so this needs to be reflected in the test.
https://github.com/alphagov/di-authentication-frontend/pull/532

GOVSI-1190: update account created page title in test

---

.gitignore
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Added a new feature to cover a scenario where a user abandons registration before 2FA setup. Followed by completion of registration to allow the account to be deleted, so local runs are kept smooth. 
To include coverage of high priority candidates for automation.

AUTH-1134: acceptance tests abandon before 2 fa setup

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/020_locked_accounts.feature

Extension of the RegistrationStepDefinitions class and addition of a new feature to cover the email and SMS OTPs being incorrectly entered 6 times, resulting in accounts being locked.
To expand automation of high priority user journeys. 

Auth 1323 acceptance tests account locked scenarios

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Adding additional step definition and other bits to cater for change of content on abandon before 2FA setup scenario.
To enable the AC tests to run successfully again

AC tests fix - abandon before 2FA setup scenario

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

Fix to enable the tests to run again
Due to changes to the title of the manage your account page in account management.

Ac tests title change tweak

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LegalAndPolicyPagesStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SupportingPages.java

Change to cookies policy constant, route, title in SupportingPages class.
To allow the AC tests to run with required changes following Daniel's implementation.

AC tests - Changes related to cookies policy page

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

AC test for error scenario during account deletion where a user enters an invalid password and is prompted to enter their password again.
To increase coverage and fulfill backlog item https://govukverify.atlassian.net/browse/AUT-48

Aut 48 acceptance tests delete account invalid password

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Addition of a feature step and step definition to cater for scenario where users reject consent to share (not on Prod atm). 
To fulfil backlog item AUT-46, and also because it's a good one to have should it ever be enabled on Production.

Added a reject consent step in the incomplete registration feature

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Addition of feature to encapsulate scenarios where an existing account management user changes their cookie policy and navigates back using the go back link. 
Also, removal of old step where an account deletion was submitted using text, replaced by targeting element by CSS for robustness.
Coverage increase, identified as valuable.

Aut 593 acceptance tests save cookie settings

---

gradle/wrapper/gradle-wrapper.properties

Downgradle gradle to 7.4.1.
The 7.5 Gradle image appears to have an issue.
#117 
https://github.com/alphagov/di-infrastructure/pull/333

AUT-612: downgradle gradle to 7.4.1

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/020_locked_accounts.feature

Additional test steps to support auth apps screens
When authenticator apps are switched on then the 'get security codes' screen appears before 'enter phone number' when creating an account.  This initial step just chooses 'text message' then continues the scenarios as before.
Add the bare minimum amount of test steps to enable auth apps to be switched on in build, and for the acceptance tests to succeed.

AUT-612: Additional test steps to support auth apps screens

---

acceptance-tests/build.gradle
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AccountManagementStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RegistrationStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthAppStub.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/NowHelper.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/003_legal_and_policy_pages.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Initial additional scenario for auth apps.
Creates an account with an auth app, logs out, then logs back in again.
Doing all this in a single scenario means there is no need to persist a secret for the auth app (for now, this can be added later as an additional scenario).
https://github.com/alphagov/di-infrastructure/pull/337

AUT-613: Initial additional scenario for auth apps

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthAppStub.java

Format the auth app security code using 6 digits and leading zeros.
A change to the auth app stub.
Leading zeros were being removed when converting the code from int to String.

BAU: Format the auth app security code using 6 digits and leading zeros

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/SignInStepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

Additional AC test scenario where an existing user switches content to Welsh. NOTE: some failures regarding to missing localisation on "Back" and "Continue" button are currently commented out and will be brought back in when the fix is in.
To increase coverage.

Aut 694 acceptance tests welsh content switch

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/LoginStepDefinitions.java

Re-enabling assertions on some translations that used to be missing. 
To include this as part of our regression.

Enabled assertion on fixed translations on buttons

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

Update Welsh test to switch back to English
As the same session is being used in the following test Welsh language is maintained, whereas the tests are checking for English.  This change is needed to due the fix for AUT-691 which has made the language behaviour consistent across applications.
https://github.com/alphagov/di-authentication-frontend/pull/765

AUT-691: Update Welsh test to switch back to English

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/015_incomplete_registration.feature

Consent to share off in the acceptance tests.
Consent to share is still switched-on in the acceptance test client because there were existing tests that had been built to use it while it was still required.  The decision has been made the consent will be off for all clients so it makes more sense to remove these steps from the tests in order to reflect what is live.
https://github.com/alphagov/di-authentication-api/pull/2215

BAU: Consent to share off in the acceptance tests

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/010_existing_user_journey.feature

Re-adding the cookie preference scenario, up to the point where a user accepts/rejects cookies. 
So these steps can be included in regression.

Re-adding the cookie scenario

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/020_locked_accounts.feature

Update the email lock test as a result of the following functional changes in ACI-7:
Do not block email when validation code entered incorrectly max times for new account.
Do not ask user to re-enter email when they request another code having exceeded the maximum.
No reason to block the account if the account does not already exist, this just means the user has to wait 15 mins before they can create the account.
Make it easier for the user by not asking them to enter their email again.
https://github.com/alphagov/di-authentication-api/pull/2408
https://github.com/alphagov/di-authentication-frontend/pull/784

ACI-7: Do not block email when validation code entered incorrectly max times for new account

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/AuthenticationJourneyPages.java

ACI-7: Add '/' to resend-email-code url
Step:
'Then the new user is taken to the resend email code page'
is failing due to the missing '/'
#149

ACI-7: Add '/' to resend-email-code url

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/020_locked_accounts.feature

Remove steps to check whether email is blocked when the user comes back having entered the security code incorrectly too many times.
Now that the email is no longer blocked we won't show the security code invalid for the email.
#150 
#149

ACI-7: Email no longer blocked

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature

Expanding the Auth app sign in feature to include no 2FA and ensuring the user is not asked to enter an OTP from the Auth app.
To have this scenario added to our regression.

Aut 799 acceptance tests auth app add sign in scenario without 2fa

---

acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/000_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/005_auth_app_2fa_journey.feature

Added the uplift scenario from Auth sign in with No 2FA as it was throwing a 500 on the GET /uplift request. 
To have this journey included in our regression.
https://github.com/alphagov/di-authentication-frontend/pull/812

Added Auth app no 2FA login followed by uplift scenario.

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java

Reset browser defaults to Firefox and non-local.
By default the pipeline uses these settings as it runs Selenium in containers and there are issues using Chrome.   They were changed as part of the refactoring in the previous PR.
#158

BAU: Reset browser defaults to Firefox and non-local

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java

Update acceptance test defaults for pipeline.
DEBUG_MODE was set to true by default, so tests where failing due to waiting for manual user input
#166

BAU: Update acceptance test defaults for pipeline

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/RegistrationPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java

Tweak of the Auth App scenario
Retrieving the SecretKey value now requires an extra step.

Auth app AC scenario tweak

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/RegistrationPage.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java

Change account created page title quote.
Spotless run on RegistrationPage.
So that it matches what's displayed in the browser, tests are currently failing in the pipeline.
#178

BAU: Change account created page title quote

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/LoginPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagement.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/NotLoggedIn.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/001_not_logged_in.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature

Remove final AM dependencies + validation error fix.
Tweak how the acceptance tests find validation errors in a page.
Remove the last things that depend on AM.  Removes the requirement for an Auth instance of AM in build.  Following this the AM tasks can be removed from the pipeline.
The PR below changed how validation errors are displayed in a page so the tests need to be updated.
https://github.com/alphagov/di-authentication-frontend/pull/898

AUT-911: Remove final AM dependencies + validation error fix

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java

Use ‘smart quotes’ when checking page titles. 
All text in the application has been updated to use smart quotes, so update the tests too.
https://github.com/alphagov/di-authentication-frontend/pull/910

AUT-1042: Use ‘smart quotes’ when checking page titles

---

reset-test-data.sh

Script to reset test data for local acceptance test runs.
The acceptance tests depend on having existing seed test users created in the right state, and also leave behind test users in the database after running.  When the tests run in the pipeline the equivalent of this script runs after the tests have completed to leave the database in a consistent state.
This script should be used to do the same when running the acceptance tests locally.  It depends on the gds cli and a working AWS account with access to the Authentication build environment.

BAU: Script to reset test data for local acceptance test runs

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocApp.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LegalAndPolicy.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AccountJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/SupportingPages.java

Acceptance test change for name change to GOV.UK One Login.
Product name is changing so tests need to be updated.

BAU: Acceptance test change for name change to GOV.UK One Login

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/SupportPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Support.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature

Removed 'Send Message' step within IPN support pages acc test and refactored accordingly.
Tests were submitting cases to the actual support desk.

AUT-1124 - stopped IPN support page test from submitting to support desk

---

README.md
acceptance-tests/build.gradle
acceptance-tests/src/test/java/uk/gov/di/test/runners/RunCucumberTest.java
acceptance-tests/src/test/resources/allure.properties

Replace Allure reporting with Cucumber reports.
IA approval decision to allow use of Allure has now been reversed. Allure no longer to be used.

AUT-1132 - replaced Allure reporting with Cucumber reports

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/SignIn.java

AUT-1162 - additional chrome option added to resolve http403 error
Additional ChromeOption added.
To resolve http403 error introduced following a chrome browser/driver update.

AUT-1162 - additional chrome option added to resolve http403 error

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java

Update page titles where changed on 'enter-code' and 'enter-authenticator-app-code'.
A related PR has changed this content.
https://github.com/alphagov/di-authentication-frontend/pull/990

AUT-995: Update page titles where changed

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature

Page title changes for password reset.
The page titles are in the feature files so were missed from a previous PR.
#223

AUT-995: Page title changes for password reset

---

README.md
reset-test-data.sh
run-acceptance-tests.sh

Option to retrieve local config from SSM rather than a .env file.
Enables a user on the VPM with AWS access to run the acceptance tests without having to worry about creating a local configuration file. 
The ready-made configuration runs the tests against the application deployed in the build environment.  At the moment there is no option to point the tests against a local running (frontend) application.
Makes it easier for everyone to run the tests.

BAU: Option to retrieve local config from SSM rather than a .env file

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature

Refactor page title on the following pages when a user uplifts from a 1FA service to 2FA. The original page titles will remain the same, and only display the new ones when uplift is required.
- `/enter-code` page to `You need to enter a security code`
- `/enter-authenticator-app-code` page to `You need to enter a security code`
So that a user signed in with 1FA understands why they are required to go through 2FA process in order to access the RP's service.
[Frontend change](https://github.com/alphagov/di-authentication-frontend/pull/996)

AUT-995: Refactor tests for uplifting from 1FA to a 2FA service

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java
acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java

Fixes test failure for duplicated test method in Login step definition
[original PR](https://github.com/alphagov/di-authentication-acceptance-tests/pull/229)

AUT-995: Refactor duplicate method in Login step definitions

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Registration.java

Change assertion expected result from 52 to 32.
To align the acc tests with the auth app secret change from 52 to 32 chars.

AUT-1201 updated secret length assertion to 32

---

reset-test-data.sh
scripts/database.sh

- Create and reset all test data in single script.
- At the moment applies to local runs only, to be applied to both pipelines.
- Move database functions to a separate script.
Allows test users and data to be created in a single place.  Can remove the user test creation job from the 'shared' component.  Removes use of terraform to create users.

AUT-1320: Create and reset all test data in single script

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java

Added capability to capture a screenshot and add it to the Cucumber report when a test fails.
- May help with debug when there are issue
- Screenshot capture on failure is a QA team requirement

AUT-1337 - added capability to capture screenshot and add to test report on failure

---

.github/workflows/build-and-push-tests.yaml
Dockerfile
reset-test-data.sh
run-acceptance-tests.sh

Update the acceptance test script parameters so they can support being used in both the CodePipeline and Concourse pipelines, as well as being run locally.
- Add a new 'r' switch to retrieve config from ssm rather than an local .env
- Read the environment from the 2nd paramater rather than the first
The scripts need to work when called from both pipelines, locally and against different target environments.
#239

BAU: Acceptance test scripts to support both pipelines and local running

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/TermsAndConditionsPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Login.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature

Removes test for users not agreeing to updated Ts&Cs
The service is being updated so that the option to select "I do not agree" is not available.
https://github.com/alphagov/di-authentication-frontend/pull/1118

AUT-1465: Remove test for not agreeing to updated Ts&Cs

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature

- Remove assertion about rejecting Ts and Cs, which points at a page that no longer exists
- After removing the possibility of rejecting new Ts and Cs, the assertion of a new page is no longer correct
- Builds on: https://github.com/alphagov/di-authentication-acceptance-tests/pull/266

AUT-1465: Remove invalid assertion

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature

Commenting out existing tests that go through support pages.
A new page has appeared (triage page?) which breaks existing tests. Commented these tests out until I know what's going on, and so as not to block the pipeline in the meantime.

deactivated support page tests until triage page confirmed

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/DocAppStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RegistrationStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RpStubStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

1. Removed references in steps to 'new' or 'existing' users, and replaced with just 'the user'.
2. Also added some code that adds a cookie so the analytics message doesn't keep appearing.
1. To reduce step duplication and will allow us to re-group the step definition files.
2. When the screenshots are taken half the screenshot is the analytics message, and also noticed that in firefox one of the tests would fail because some text it was looking for was off the screen (due to the analytics message)

AUT-1888 removed references that specify new or existing user

---

.github/CODEOWNERS

Add codeowners file for new org
The codeowners file did not actually exist before now.

BAU: Add codeowners file for new org

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Enforce_100k_password_check.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Reset_password.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

Resolved unneccessarily long waits when checking for element non presence, and resolve issue with log out steps where it sometimes went out of sync
1. Resolved unneccessarily long waits when checking for element non presence
2. Resolved occasional issue where the log out steps went out of sync
1. To reduce execution time (particularly in Firefox)
2. To reduce test failures

AUT-1944 - resolved unneccessarily long waits when checking for elements non presence

---

Dockerfile
acceptance-tests/src/test/java/uk/gov/di/test/pages/BasePage.java
run-acceptance-tests.sh

Please include a summary of the change.
AUT-1174 : Switch acceptance tests to run on Chrome in the pipeline
This Change is to run acceptance test in pipeline to run on Chrome Browser

Changing Acceptance test to run on Chrome browser

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

Remove redundant tests.
2FA changes mean that 2 of the account recovery tests are now redundant.

removed now redundant tests following 2fa change

---

reset-test-data.sh
run-acceptance-tests.sh
scripts/export_aws_creds.sh

Use AWS CLI profiles to access AWS accounts, rather than gds-cli.
Standardising with other repositories.

AUT-2485: use new pattern for accessing AWS accounts

---

run-acceptance-tests.sh
scripts/export_aws_creds.sh

If deploying in codebuild, don't try to export AWS credentials.
They're all in the environment already.
Codebuild sets various envars that we don't have locally: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
We check if one of these exists: if it does, do nothing and just unset AWS_PROFILE.

AUT-2485: Fix pipeline deploy

---

scripts/database.sh

Additional logging for internal common subject id creation.
There are errors creating users for account interventions testing when running in the pipeline.
Provides more context for the errors:
`warning: command substitution: ignored null byte in input`

BAU: Additional logging for internal common subject id creation

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/AuthenticationJourneyPages.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature

Updates the title for the enter code screen presented on uplift journeys
To reflect changes to the title and heading introduced in https://github.com/govuk-one-login/authentication-frontend/pull/1438
- https://github.com/govuk-one-login/authentication-frontend/pull/1438

AUT-1540: Update title for the enter code screen on uplift journeys

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature

Uncommented previously disabled steps in Account Intervention tests
These steps are now able to run.

uncommented previously disabled tests steps

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature

Update tests to reflect change in page heading
The page heading has been updated in response to findings from user research
- https://github.com/govuk-one-login/authentication-frontend/pull/1538

AUT-2021: Test update to reflect copy change

---

docker-compose.yml
reset-test-data.sh
run-acceptance-tests-against-dev-env.sh

Changes to allow users to run against a dev environment
We need this so users can run ac tests against their changes without merging into main
A full description of the problem and the implementation of this PR has been done on [this confluence page](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4193812628/Running+acceptance+tests+locally).

BAU: run acceptance tests against dev environments

---

acceptance-tests/build.gradle
acceptance-tests/src/test/java/uk/gov/di/test/pages/UserInformationPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Account_management_apis.feature
reset-test-data.sh
scripts/reset-account-management.sh

Create an acceptance test that verify that the internal account management update password API is un and running correctly.
We need automated tests for internal am APIs.

AUT-3386: Create api acceptance test for update password

---

.github/workflows/build-and-push-tests-SP.yaml

Issue: [AUT-3504]
Sign acceptance-tests image with Container Signer key, in the SP GitHub workflow
Following the secure pipeline image signing standards
[AUT-3504]: https://govukverify.atlassian.net/browse/AUT-3504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3504 - Sign acceptance-tests image with Container Signer key

---

acceptance-tests/build.gradle

Bumped surefire plugin version to 3.4.0
It was out of date and dependabot didn't work.

BAU - bumped surefire plugin version

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/RpStubPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java

Also revert the previous commit that put this on RPStub page loads. Didn't work in the end due to the cookie we care about being on a different domain than the stub page.
Useful for associating sessions from acceptance tests with AWS resource logs
https://github.com/govuk-one-login/authentication-acceptance-tests/pull/409

BAU: Print the user session ID on after all page loads to the console

---

.github/workflows/build-and-push-tests-SP.yaml
.github/workflows/build-and-push-tests-dev.yaml
Dockerfile.sp
run-tests.sh
scripts/database.sh

- Separate Dockerfile and entrypoint for Secure pipelines deployment
- In `scripts/database.sh`, optional switch to assume role to old account to reset test data, see docs https://govukverify.atlassian.net/wiki/spaces/LO/pages/4485349685/Cross-account+acceptance+tests+run
- (Tech debt reconciliation) Bump aws-actions GHAs to node20 compliant
Issue: [AUT-3549]
Auth-deploy-pipeline and sam-deploy-pipeline have some differences in test stage execution logic, sam pipeline being more generic. Changes required in Dockerfile and docker entrypoint script. Though acceptance-tests run from old environments must not break. Hence setup separate dockerfile and entrypoint script. 
https://github.com/govuk-one-login/authentication-api/pull/5169 …

AUT-3549 - Acceptance test configurations for secure pipeline compatibility

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Lockouts_sign_in.feature

Temporarily comment incorrect password reset test.
The test is currently flakey and failing often in the pipeline.

BAU: Temporarily comment incorrect password reset test

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/Driver.java
run-acceptance-tests.sh

Run selenium locally rather than starting and connecting to the remote selenium containers.
Don't start and stop the selenium containers.
Set SELENIUM_LOCAL to false by default
Tested by pushing the image to the dev environment and running the tests in the pipeline (note that tests don't all run successfully in dev at the moment, but the fact that any tests can run proves that the change works.
Before change, note 
`
Container test-selenium-firefox-1  Creating
Container test-selenium-chrome-1  Creating
`
https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/761723964695/projects/Test-build-auth-deploy-pipeline/build/Test-build-auth-deploy-pipeline%3A0c382c28-f129-4c9b-83ab-dd291404db66/?region=eu-west-2
After change no selenium containers started: …

AUT-3710: Run selenium locally rather than starting and connecting to the remote selenium containers

---

acceptance-tests/build.gradle
acceptance-tests/src/test/resources/cucumber.properties

Reverts govuk-one-login/authentication-acceptance-tests#402
This is so that we can try rolling back to a known good baseline of dependencies before our pipeline acceptance tests became flakey.

Revert "BAU - updated dependency versions, removed duplicationa and redundant…"

---

acceptance-tests/build.gradle

Reverts govuk-one-login/authentication-acceptance-tests#405
This is so that we can try rolling back to a known good baseline of dependencies before our pipeline acceptance tests became flakey.

Revert "BAU - bumped surefire plugin version"

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/ReenterYourSignInDetailsToContinuePage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java

Updates the acceptance tests to reflect content update.
The re-auth page asking users to re-enter their sign-in details page content is being updated. 
https://github.com/govuk-one-login/authentication-frontend/pull/2057 introduces the content update this change relates to

AUT-3685: Update strings to reflect content update

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/003_legal_and_policy_pages.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/006_registration_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/IPN.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Reauthentication.ZZZfeature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

Previously, we checked that log-out had succeeded for almost every logout attempt. Now, use the lazy "click the box and run away" method unless we are reusing the browser session.
As we are currently having intermittent issues with confirming logout, this will reduce the number of times we could possibly encounter that situation.

BAU: Reduce the number of checked logouts

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/005_auth_app_2fa_journey.feature

Clear cookies to simulate logout.
Some tests are getting stuck waiting for logout to complete on the RP stub in the pipeline, which is causing tests to fail.  A workaround was to stop waiting for logout to complete as this was the last step in most tests.  However, where there was a dependency on logout completing for the next scenario to continue this could not be done.
Instead do not wait for logout to complete before the next step, but clear cookies so that the user's session is effectively cleared, and they will start the journey again.
#418

BAU: Clear cookies to simulate logout

---

run-tests.sh

Cucumber flag and better error handling for SP endpoint
Issue: [AUT-3542]
Removed hardcoded cucumber test flag for secure pipeline deployments
[AUT-3542]: https://govukverify.atlassian.net/browse/AUT-3542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3542 - Cucumber flag and better error handling for SP endpoint

---

.pre-commit-config.yaml
build.gradle
run-acceptance-tests-against-dev-env.sh
run-acceptance-tests.sh

Explicitely forbid spotless from running in `run-acceptance-tests*`.
It should already be done by this point, and spotless seems sad now.
Code review should do it

BAU: Don't run spotless when testing

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RpStubStepDef.java

Previously, the retry counter would increase *every time* `doRpStubAndWaitForSignInPage()` was called. Obviously this means that after 5 calls to the method, it has always exceeded the limit. Essentially it acted as a call counter.
Now, we don't increment the retry counter *until* the function has been called with a throwable, ie. we don't ever retry until it's previously failed. ie. we actually count retries, not just tries.

BAU: fix retry methodology

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RpStubStepDef.java

Cookies were being deleted before out of an abundance of caution.
This is actually disruptive in the case of SSO uplift - we need
to keep the existing session in place.
In theory, if we are retrying the RP stub, it means that no
session stuff has actually happened at that point, so there's no
actual need to clear them when retrying.
This has the side effect of fixing the uplift edge case without
writing any more java.

BAU: Don't delete cookies when retrying the stub

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Reauthentication.feature

Fix logout issue with reauth tests.
The way logouts are handled in the tests has changed as the logout step was proving flakey.  This change brings the new reauth tests into line with the flake fixes.
1. Code Review
1. Run the tests against a dev/test environement
#446

BAU: Fix logout issue with reauth tests

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/OneLoginSession.java

Adds the new "bsid" cookie to the OneLoginSession. As far as I can tell, this class is only used for logging on error. 
There are no tests which close and reopen the browser (which would delete this cookie and sign a user out), so I believe this is the only change needed.
1. Code Review

ATO-1013: add bsid cookie to OneLoginSession

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/OneLoginSession.java

This seems to be masking other test failures

BAU: ensure we don't call methods on null

---

acceptance-tests/src/test/java/uk/gov/di/test/utils/OneLoginSession.java

This reverts commit 2d3a1f22c278dee570d249cc504b9584a2f3670a, PR https://github.com/govuk-one-login/authentication-acceptance-tests/pull/438
This was previously added as the bsid cookie was going to be on the `account.gov.uk` domain, but this changed to be `oidc.account.gov.uk`, meaning on none of these pages would the `bsid` cookie be accessible. 
1. Code Review

Revert "ATO-1013: add bsid cookie to OneLoginSession"

---

acceptance-tests/build.gradle

Revert surefire back to previously-working version, bump AWS sdk to latest

BAU: Revert surefire to 3.2.5

---

README.md

Readme updates to explain how to use aws config from the parameter store to run the acceptance tests locally against envs other than build.
1. Code Review

BAU: Add instructions to readme for generating env files for different envs

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/ReenterYourSignInDetailsToContinuePage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/RpStubStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/UserLifecycleStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/World.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Reauthentication.feature

Introduce the concept of a second User whose details can be used by the logged-in User.  The second User details can then be used to check that their misuse by another User does not prevent them from logging in or re-authenticating.
Fixed the commented out tests so they work using the recent changes to the step code.  One of the tests has highlighted an error in the production once it was running so that test has been commented out until the bug is fixed.
1. Code Review
2. Run tests against an environment such as staging.
3.

AUT-3802: Fix failing reauthentication test.

---

acceptance-tests/build.gradle

Revert Selenium to 4.11.0
Later versions are suspected of causing acceptance test flakes.  4.5.0 appeared to be better, but this version does not contain Selenium Manager (https://www.selenium.dev/documentation/selenium_manager/) whose features we would like to use, so rolling back to the earliest version with Selenium Manager for Chrome (4.11.0)
The change has been tested by a local acceptance test run against build.
1. Code Review
1. Local acceptance test run against the build environment
There was a noticeable drop in success rates after this: https://github.com/govuk-one-login/authentication-acceptance-tests/commit/9a77a4bba16b8bb130c8cd42fb940082a2d6ee42#diff-754c42c3563eb7a6a9f94cc57e69fc84a5015de90c4c50c16e64341495607145L21 …

BAU: Revert Selenium to 4.11.0

---

.github/dependabot.yml

Ignore selenium-java versions > 4.11.0
Later versions suspected of causing acceptance test flakes
1. Code Review
See #481

BAU: Ignore selenium-java versions > 4.11.0

---

acceptance-tests/build.gradle

Reverts govuk-one-login/authentication-acceptance-tests#545
Starting to see flakey tests, so revert this bump which includes selenium (as we've seen these kind of bumps cause issues in the past)

Revert "BAU: Bump the gradle-all-dependencies group across 1 directory with 2 updates"

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

Updated Account Receovery feature tests below specific to MFA reset changes failing in dev pipeline 
An sms user can change how they get security codes and log in with new method (Dev Test Only) 
An auth app user can change how they get security codes and log in with new method (Dev Test Only)
Review the existing functional;ity for MFA Reset success page and subsequent logout

Changes to fix two MFA Reset specific tests failing in Dev due to changes in success page post MFA Reset in accpunt recovery feature

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

This PR addresses the issue of failing tests that were unable to access the contact page, resulting in a 403 error. The issue has been resolved by validating the page using its URL. A manual check has also been conducted to confirm that the page displays the expected content.
Additionally, the tagging issue has been resolved. All tests tagged with @old-mfa-without-ipv are now excluded from running in the dev environment but will run successfully in the build environment without any issue and @Under-Development will not run in build as MFA-Reset is not turned on.

Address failing tests in build and ensure tagging are working as expected

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature

This PR is related to the previous failing tests in the pipeline that has been fixed and now, we are removing the "@does not work from pipeline" tagging

Remove does not work tagging as all tests have fixed and working

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/010_existing_user_journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/account_recovery.feature

This PR removes the @underdevelopment tag and which previously prevented these scripts from running the acceptance tests in the build due to MFA being turned off. Now MFA will be enabled to allow acceptance tests to run in the build environment, these tests will run to ensure all testing is completed before we can sign-off for go live.

@underdevelopment tag has been removed

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Mfa_reset.feature

While we have two pipelines we will need two run the acceptance tests against two build environments.  One of these will have the new MFA reset with IPV feature switched on, the new secure pipeline, the other will have it switched off, the old pipeline.
When we enable the new MFA reset we will use tags
as follows:
@new-mfa-reset-with-ipv in old build to exclude mfa tests 
@old-mfa-without-ipv in new build to exclude old mfa tests
1. Code Review

AUT-4047: Separate old and new mfa tests

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/account_interventions.feature

Build SP migration - suspend old mfa reset tests.
Tests suspended as they need to be adapted to the new mfa reset journey.  They are currently failing in the backend pipeline where mfa reset was not switched on before migration to SP
1. Code Review

BAU: Build SP migration - suspend old mfa reset tests

---

.github/workflows/build-and-push-tests-SP.yaml
.github/workflows/build-and-push-tests.yaml

As part of an investigation into why acceptance test images are not being build with latest changes we tried `--no-cache`. This is no longer required.
1. Code Review

BAU: Revert tmp changes that disable cache

---

docker/run-tests-sp.sh

Run #cores+1 tests in parallel. Ideally it'd be 1:1, but as there are waits in some of the tests, a bit of context switching is acceptable.
- Code review
- Check reasoning is sound

BAU: run #cores+1 tests at once

---

docker/run-tests-sp.sh
rundocker.sh

Our frontend in the new AWS account for secure pipeline requires a cross account role so we can test the new frontend, but against the old backend.
This configures the scripts to do so.
Can be executed with `./rundocker.sh dev-sp`.
SSM parameters have been set up in the new account so it loads the correct acceptance test configuration.
1. Code Review

BAU: Allow rundocker.sh to target dev-sp

---

.github/workflows/build-and-push-tests-SP-dev.yaml

Workflow to deploy branch images to new SP Dev account
Deploys to `di-authentication-development` account `acceptance-tests-image-repository` 
IAM Role used: frontend-pipeline GitHubActionsRoleArn from the same account
Same as [build-and-push-tests-SP.yaml](https://github.com/govuk-one-login/authentication-acceptance-tests/blob/main/.github/workflows/build-and-push-tests-SP.yaml), except the role to assume and repository to push are different, and specific to dev account

AUT-4202: Workflow to deploy branch images to new SP Dev account

---

.github/workflows/build-and-push-tests-SP-dev.yaml

Use dev container signer key for [build-and-push-tests-SP-dev.yaml](https://github.com/govuk-one-login/authentication-acceptance-tests/blob/main/.github/workflows/build-and-push-tests-SP-dev.yaml)

AUT-4202: Use new dev container signer key

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/StubStartPage.java
acceptance-tests/src/test/java/uk/gov/di/test/services/UserLifecycleService.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature

There is code in the authentication-api that ensures that only normalised phone numbers are stored.  That means all phone numbers will have the international dialing code prefixed.  Therefore any test data created by updating DynamoDB directly also needs to be in this format.
1. Code Review

AUT-1416: Fix migrated user creation

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/MFAMethodsAPIStepdefs.java

The test scenario of a User with a backup auth app not being allowed to change the default to an auth app was not checking the correct response status code.
1. Code Review

AUT-4309: Fix default method change to Auth App test

---

docker/run-tests-sp.sh

Option to use API_RP_URL if the test stage is on backend pipeline.
Introduced a new optional SSM parameter `API_RP_URL`, if defined and `SAM_STACK_NAME="authentication-api"`, then the URL replaces current `RP_URL`.
Issue: [AUT-4345]
See JIRA ticket [AUT-4345] for detailed local testing instructions
[AUT-4345]: https://govukverify.atlassian.net/browse/AUT-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4345]: https://govukverify.atlassian.net/browse/AUT-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4345: Option to use API_RP_URL if the test stage is on backend pipeline

---

docker/run-tests-sp.sh

Optional API_STUB_RP_TYPE and API_CUCUMBER_FILTER_TAGS env overrides
IF the test container identifies it is running on a pipeline where SAM_STACK_NAME = "authentication-api",
then it can replace several SSM parameters with their API_~ equivalent. Supported settings are:
- API_RP_URL
- API_STUB_RP_TYPE
- API_CUCUMBER_FILTER_TAGS
Issue: [AUT-4345]
See jira ticket [AUT-4345] for a detailed test setup
[AUT-4345]: https://govukverify.atlassian.net/browse/AUT-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4345]: https://govukverify.atlassian.net/browse/AUT-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4345: Optional API_STUB_RP_TYPE and API_CUCUMBER_FILTER_TAGS env overrides

---

acceptance-tests/src/test/java/uk/gov/di/test/pages/SupportPage.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/SupportStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/account_management.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-auth-app-user.feature
acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/migrated-user-scenarios/mfa-methods-default-sms-user.feature

The PR covers acceptance tests for checking try another way to get security code for MFA hyperlink and consequent page to display both default and backup MFA's for user to check and request security code.
This covers below 2 tickets for users with both MFA's as SMS phone number and user with Auth App as default and SMS as backup MFA 
https://govukverify.atlassian.net/browse/AUT-4247
https://govukverify.atlassian.net/browse/AUT-4248

AUT-4247 Create 'Check your phone screen' (Auth App/SMS user) and AUT-4248 Create 'Check your phone screen' (SMS/SMS user)

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CrossPageFlows.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/LoginStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature

AUT-4183 User selects backup MFA to reset pasword
Scnario's. covered
1. Auth Default Backup SMS reset passord using backup MFA successfully 
2. SMS Default Backup Auth App reset passord using backup MFA successfully 
3. Error Screen for trying incorrect OTP for backup MFA 6 times
4. Error Screen for requesting OTP for backup MFA 6 times

AUT-4183 User selects back-up MFA for password reset

---

acceptance-tests/src/test/java/uk/gov/di/test/entity/UserProfile.java
acceptance-tests/src/test/java/uk/gov/di/test/services/ApiInteractionsService.java
acceptance-tests/src/test/java/uk/gov/di/test/services/UserLifecycleService.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/AccountManagementStepDef.java
acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/UserLifecycleStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/api/account-management/account_management.feature

Add a test for migrated Users trying to reuse a phone number. Use correct data for un-migrated users - ensure they don't have a verified phone number when they are an auth app user.
1. Code Review

AUT-4320: Account Management Send OTP

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/Hooks.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature

- Adds acceptance tests for when a user with 2 migrated mfa methods goes
through an uplift journey, from this ticket onwards they will be see
the 'try another way' prompt on the enter code screen instead of the
'check if you can change how you get security codes' prompt
- I've also added an @after hook that deletes all cookies. This is because
the user session was persisting between test cases. This change resolves this.
- - In future, might be a good idea to consolidate Hooks logic
1. Code Review
2. Run against AUT-4199/back-up-mfa-uplift FE repo branch
- - - Both locally and in dev pipeline
https://github.com/govuk-one-login/authentication-acceptance-tests/pull/683

Aut 4199/back up mfa uplift

---

acceptance-tests/src/test/resources/uk/gov/di/test/features/Cookies.feature

This reverts commit 974141081d3df492ca5f9bbd03c73bf04ab00826 (enabling the device intelligence cookie test), due to the test failing in the pipeline. Will revert, investigate, fix, and re-enable.

Revert "AUT-4334: Enable test for device intelligence cookie"

---

.git-blame-ignore-revs
README.md
rundocker.sh

- Instead of partially hardcoding the selenium base image, instead allow
the user to specify the whole image name + version as an argument.
This ensures that if no image is specified, the default _from the
Dockerfile_ is used. As-was, we would have to remember to bump the
version both in this script and the Dockerfile, which is error-prone.
- Remove `--privileged` flag from `docker run` commands, as it is not
needed for these tests and can pose security risks.
WRT the base image, I could have added some guardrails to prevent people using inappropriate base images, but it'll become very clear when the tests don't work. It's unlikely this flag will be used very often.
Run the script with/without a specified base image - check tests work as expected (spurious AT failures don't necessarily …

BAU: minor improvements to rundocker.sh

---

acceptance-tests/src/test/java/uk/gov/di/test/step_definitions/CommonStepDef.java
acceptance-tests/src/test/resources/uk/gov/di/test/features/Login/using-back-up-mfa.feature

This PR updates the logic for the phone_number_verified claims in the auth user-info response, based on changes to how default and backup MFA methods are handled.
Previously, only SMS MFA users had their phone number included, and it was blank for Auth App users. With upcoming changes allowing default/backup combinations, only the default MFA method will determine whether a phone number is returned.

AUT-4315- To validate Update rules for phone number

---

docker/run-tests-ui.sh

Ensure the UI entrypoint script always reads a single entry for these configs: API_RP_URL, API_STUB_RP_TYPE and API_CUCUMBER_FILTER_TAGS.
Given any of the above configs are overridden in env-override-ui.env, ensure the last entry is read.
How to test, steps:
1. Inject an env var in the docker run `-e SAM_STACK_NAME="authentication-api" \`
2. Run `./rundocker.sh dev-ui`

AUT-4503: API_ overrides to work with local env files

---

acceptance-tests/build.gradle

Bump apache.commons to 3.18.0
1. Code Review

BAU: Bump apache.commons to 3.18.0

---

acceptance-tests/build.gradle

The previously added constraint did not apply to the plugins so adding a constraint in the root buildScript that applies to the plugins.
1. Code Review
- Approach cribbed from https://github.com/govuk-one-login/authentication-api/pull/6910

BAU: Fix CVE-2025-48924 in gradle plugins

---

acceptance-tests/build.gradle

Reverts govuk-one-login/authentication-acceptance-tests#762

Revert "BAU: Bump apache.commons to 3.18.0"
